receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    limit_mib: 512
    check_interval: 15

exporters:
  debug:
    verbosity: detailed
  # Prometheus for metrics
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      service: "permomap"
  # OTLP HTTP exporter for Loki - DISABLED
  otlphttp:
    endpoint: http://0.0.0.0:3100/otlp
  otlphttp/jaeger:
    endpoint: "http://jaeger:4318" # URL for Jaeger's OTLP HTTP receiver
    tls:
      insecure: true

  # Jaeger exporter - DISABLED
#  jaeger:
#    endpoint: jaeger:14250
#    tls:
#      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
#      processors: [memory_limiter, batch]
      exporters: [otlphttp/jaeger, debug]
    metrics:
      receivers: [otlp]
#      processors: [memory_limiter, batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
#      processors: [memory_limiter, batch]
      exporters: [otlphttp, debug]

  extensions: []
