name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Images
        run: docker compose build

      - name: Start Containers
        uses: hoverkraft-tech/compose-action@v2.4.0
        with:
          compose-file: "docker-compose.yml"

      - name: Wait for Services to be Ready
        run: |
          echo "Pausing for 20 seconds to allow containers to initialize..."
          sleep 20
          docker compose ps
          echo "Container status check complete."

      - name: Run Integration Tests
        run: |
          echo "Executing integration tests..."
